import type { Metadata } from 'next';
import { Poppins as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';

export const fontSans = FontSans({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
        <div className='header'>Header</div>
        <main>{children}</main>
        <div className='footer'>Footer</div>
      </body>
    </html>
  );
}
